package com.codecool.krk.enums;

public enum ECategory {
    MILF, LESBIAN, BDSM, TEEN, BBC, AMATEUR, ANAL, ARAB, ASIAN, BABE, BBW, BIG_ASS, BIG_DICK, BIG_TITS, BLONDE, BJ, BONDAGE, BRUNETTE, BUKKAKE, CARTOON, CELEBRITY,
    COMPILATION, COLLEGE, CUMSHOT, CZECH, DP, FEET, FETISH, FISTING, FRENCH, FUNNY, GANGBANG, GAY, HANJOB, HARDCORE, HENTAI, INDIAN, INTERRACIAL, ITALIAN, JAPANESE, KOREAN,
    LATINA, MATURE, MASSAGE, MASTURBATION, ORGY, PARODY, PARTY, PISSING, PORNSTAR, POV, PUBLIC, PUSSY_LICKING, REALITY, RED_HEAD, ROLE_PLAY, ROMANTIC, ROUGH_SEX, RUSSIAN,
    SCHOOL, SFW, SMALL_TITS, SMOKING, SOLO_FEMALE, SQUIRT, STEP_FANTASY, STRIPTEASE, TATTOED_WOMEN, THREESOME, TOYS;
}